services:
  node: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    networks:
      - mariadb

networks:
  mariadb:
    external: true